### ISSUE TITLE
Missing keys when generating new samples

### ISSUE THREAD

**Issue by rahulbhalley** [rosinality/style-based-gan-pytorch#27]
I downloaded the generator parameters provided by you here: https://github.com/rosinality/style-based-gan-pytorch/issues/3#issuecomment-463173256. But I keep getting missing key(s) error as following:

```
(base) Rahuls-MacBook-Pro:style-based-gan-pytorch rahulbhalley$ python generate.py 
Traceback (most recent call last):
  File "generate.py", line 9, in <module>
    generator.load_state_dict(torch.load('checkpoint/style-gan-600k.model', map_location=device))
  File "/Users/rahulbhalley/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for StyledGenerator:
	Missing key(s) in state_dict: "generator.progression.1.conv1.1.conv.bias", "generator.progression.1.conv1.1.conv.weight_orig", "generator.progression.1.conv1.2.weight", "generator.progression.1.conv1.2.weight_flip", "generator.progression.2.conv1.1.conv.bias", "generator.progression.2.conv1.1.conv.weight_orig", "generator.progression.2.conv1.2.weight", "generator.progression.2.conv1.2.weight_flip", "generator.progression.3.conv1.1.conv.bias", "generator.progression.3.conv1.1.conv.weight_orig", "generator.progression.3.conv1.2.weight", "generator.progression.3.conv1.2.weight_flip", "generator.progression.4.conv1.1.conv.bias", "generator.progression.4.conv1.1.conv.weight_orig", "generator.progression.4.conv1.2.weight", "generator.progression.4.conv1.2.weight_flip", "generator.progression.5.conv1.0.weight", "generator.progression.5.conv1.0.bias", "generator.progression.5.conv1.1.weight", "generator.progression.5.conv1.1.weight_flip", "generator.progression.6.conv1.0.weight", "generator.progression.6.conv1.0.bias", "generator.progression.6.conv1.1.weight", "generator.progression.6.conv1.1.weight_flip", "generator.progression.6.noise1.weight_orig", "generator.progression.6.adain1.style.linear.bias", "generator.progression.6.adain1.style.linear.weight_orig", "generator.progression.6.conv2.conv.bias", "generator.progression.6.conv2.conv.weight_orig", "generator.progression.6.noise2.weight_orig", "generator.progression.6.adain2.style.linear.bias", "generator.progression.6.adain2.style.linear.weight_orig", "generator.progression.7.conv1.0.weight", "generator.progression.7.conv1.0.bias", "generator.progression.7.conv1.1.weight", "generator.progression.7.conv1.1.weight_flip", "generator.progression.7.noise1.weight_orig", "generator.progression.7.adain1.style.linear.bias", "generator.progression.7.adain1.style.linear.weight_orig", "generator.progression.7.conv2.conv.bias", "generator.progression.7.conv2.conv.weight_orig", "generator.progression.7.noise2.weight_orig", "generator.progression.7.adain2.style.linear.bias", "generator.progression.7.adain2.style.linear.weight_orig", "generator.progression.8.conv1.0.weight", "generator.progression.8.conv1.0.bias", "generator.progression.8.conv1.1.weight", "generator.progression.8.conv1.1.weight_flip", "generator.progression.8.noise1.weight_orig", "generator.progression.8.adain1.style.linear.bias", "generator.progression.8.adain1.style.linear.weight_orig", "generator.progression.8.conv2.conv.bias", "generator.progression.8.conv2.conv.weight_orig", "generator.progression.8.noise2.weight_orig", "generator.progression.8.adain2.style.linear.bias", "generator.progression.8.adain2.style.linear.weight_orig", "generator.to_rgb.6.conv.bias", "generator.to_rgb.6.conv.weight_orig", "generator.to_rgb.7.conv.bias", "generator.to_rgb.7.conv.weight_orig", "generator.to_rgb.8.conv.bias", "generator.to_rgb.8.conv.weight_orig". 
	Unexpected key(s) in state_dict: "generator.progression.1.conv1.conv.bias", "generator.progression.1.conv1.conv.weight_orig", "generator.progression.2.conv1.conv.bias", "generator.progression.2.conv1.conv.weight_orig", "generator.progression.3.conv1.conv.bias", "generator.progression.3.conv1.conv.weight_orig", "generator.progression.4.conv1.conv.bias", "generator.progression.4.conv1.conv.weight_orig", "generator.progression.5.conv1.conv.bias", "generator.progression.5.conv1.conv.weight_orig". 
```

From your README it looks like you've recently modified the network architecture, therefore, this error is occurring. Could you please upload **new parameters of both generator and discriminator networks** for us to use for further training and high resolution image synthesis? It would be really helpful for me as I am basing my research work on this implementation and particularly your implementation looks pretty nice to me. 

By the way thanks a lot for open-sourcing such a nice and simple implementation of StyleGAN in PyTorch. 🙂

**Comment by rosinality** [comment]
I have uploaded checkpoints and made links at e5caa16. Hope this helps!

**Comment by rahulbhalley** [comment]
Thanks you!
