### ISSUE TITLE
TypeError: forward() missing 1 required positional argument: 'input'

### ISSUE THREAD

**Issue by MichaelMonashev** [rosinality/style-based-gan-pytorch#46]
```
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python3 train.py --mixing --loss r1 --sched --phase 16 train-full
Size: 256; G: 2.811; D: 3.419; Grad: 0.003; Alpha: 1.00000:   0%|                                                       | 13/30000 [01:08<17:22:00,  2.08s/it]Traceback (most recent call last):
  File "train_v3.py", line 345, in <module>
    train(args, dataset, generator, discriminator)
  File "train_v3.py", line 133, in train
    real_scores = discriminator(real_image, step=step, alpha=alpha)
  File "/home/michael/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/michael/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/michael/.local/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/michael/.local/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/michael/.local/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in replica 4 on device 4.
Original Traceback (most recent call last):
  File "/home/michael/.local/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/michael/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'input'

Size: 256; G: 2.811; D: 3.419; Grad: 0.003; Alpha: 1.00000:   0%|                                                     | 13/3000000 [01:14<48:01:02,  5.76s/it]
```

**Comment by hblflybird** [comment]
Same issue, you could try adding drop_last=True in Dataloader in sample_data function in train.py

**Comment by MichaelMonashev** [comment]
I added `drop_last=True` in Dataloader, but got this error again.

**Comment by MichaelMonashev** [comment]
Sometimes this error is raised on 128 resolution, sometimes not.

**Comment by mehameha998** [comment]
Maybe some images in your dataset have crashed?

**Comment by mackenziebeggs** [comment]
I had the exact same issue, increasing the batch size (args.batch_default in my case) helped.

**Comment by mackenziebeggs** [comment]
I had the exact same issue and increasing the default batch size helped me.
