### ISSUE TITLE
Error when training

### ISSUE THREAD

**Issue by zhangdan8962** [rosinality/style-based-gan-pytorch#76]
Hi, 
I encountered the following error at some point of the training. Is anything wrong with the data itself?

Size: 8; G: 2.545; D: -1.655; Grad: 0.155; Alpha: 1.00000:   0%|▏                                                                                                       | 6331/3000000 [55:53<419:29:32,  1.98it/s]Traceback (most recent call last):
  File "train.py", line 344, in <module>
    train(args, dataset, generator, discriminator)
  File "train.py", line 127, in train
    real_predict = discriminator(real_image, step=step, alpha=alpha)
  File "/home/dzhang4/miniconda3/envs/test/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/dzhang4/miniconda3/envs/test/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/dzhang4/miniconda3/envs/test/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/dzhang4/miniconda3/envs/test/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/dzhang4/miniconda3/envs/test/lib/python3.7/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in replica 7 on device 7.
Original Traceback (most recent call last):
  File "/home/dzhang4/miniconda3/envs/test/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/dzhang4/miniconda3/envs/test/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'input'

**Comment by rosinality** [comment]
I think it is related to split of batches in DataParallel. Maybe adding drop_last to DataLoader will help. https://github.com/rosinality/style-based-gan-pytorch/blob/master/train.py#L35
