### ISSUE TITLE
CUDNN_STATUS_NOT_SUPPORTED

### ISSUE THREAD

**Issue by edebrouwer** [rosinality/style-based-gan-pytorch#83]
Hi, I'm having this error while trying to train the model on CelebA dataset : 

Traceback (most recent call last):
  File "train.py", line 347, in <module>
    train(args, dataset, generator, discriminator, device)
  File "train.py", line 167, in train
    fake_predict.backward()
  File "/home/edward/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/edward/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.

I'm running Python 3.6.4 with torch 1.4.0. Nvidia-driver 418.56

Any idea where I could look for some fix ?

Thanks so much !

Edward

**Comment by rosinality** [comment]
Could you give me the error logs with CUDA_LAUNCH_BLOCKING=1?

**Comment by edebrouwer** [comment]
I have exactly the same error logs with CUDA_LAUNCH_BLOKCING=1

**Comment by rosinality** [comment]
Could you check output dimensions? Sometimes this kind of error happens when tensor is too large.

**Comment by edebrouwer** [comment]
I tried with smaller batch sizes and it still fails on the lowest resolution.

**Comment by rosinality** [comment]
Sorry but it is hard to know why...

**Comment by Dimbl4** [comment]
@edebrouwer try to upgrade torch 1.4.0 to nightly, it helped me. (cuda 10.0, torch 1.5.0.dev20200313+cu100)

**Comment by KelestZ** [comment]
Same issue. Did any fix it?

**Comment by seongeunso** [comment]
I had same issue in here, so I downgrade the torch version.
For me, torch 1.2.0 + cuda 10.0 works well ([link](https://pytorch.org/get-started/previous-versions/#linux-and-windows-1))
